<template>
<footer aria-label="Site Footer" class="bg-gray-50">
  <div class="mx-auto max-w-screen-xl px-4 py-8  lg:px-8">
    <div class="flex items-center justify-between">
      <div class="flex justify-center text-teal-600 justify-start">
        <img
          class="h-8"
          viewBox="0 0 28 24"
          fill="none"
          src="/vuejs.png"
        />

      </div>

      <p class="mt-3 text-center text-sm text-gray-500 mt-0 text-right">
        Copyright &copy; 2022. All rights reserved.
      </p>
    </div>
  </div>
</footer>
    
    
</template>